### ISSUE TITLE
predictive entropy search without sampling

### ISSUE THREAD

**Issue by xunhuan-li** [josejimenezluna/pyGPGO#19]
Hi there,

Thanks for your package!
We noticed that the the predictive entropy search in the file acquisition.py is different from the method introduced by the paper "Predictive Entropy Search for Efficient Global Optimization of Black-box Functions".

It seems, the method in the package only calculates the approximation of H[p(y|Dn; x; x*)] and did not sample x* based on estimated posterior distribution and take average of the approximated H[p(y|Dn; x; x*)].

**Comment by hawk31** [comment]
Hello @xunhuan-li,

If you implement said acquisition function I'd gladly accept a PR :grin: 

Best,
