### ISSUE TITLE
Does this tool support BO with constrains?

### ISSUE THREAD

**Issue by xunzhang** [josejimenezluna/pyGPGO#25]
Have you implemented the idea from "Bayesian Optimization with Inequality Constraints" in current acquisition function? Thanks.

**Comment by josejimenezluna** [comment]
Hello @xunzhang -- constrained optimization routines are not currently implemented in the library. I am happy to receive a PR with such functionality.

**Comment by sgbaird** [comment]
Maybe check out [Ax](https://github.com/facebook/Ax) (not affiliated) if you need inequality constraints (I came here seeing if pyGPGO could handle equality constraints).
