### ISSUE TITLE
Covariance function bounds being overwritten

### ISSUE THREAD

**Issue by bacalfa** [josejimenezluna/pyGPGO#29]
This [line](https://github.com/josejimenezluna/pyGPGO/blob/295a7b17b0358ee73ad554e487961635986fdadc/pyGPGO/surrogates/GaussianProcess.py#L130) discards user-defined bounds on the covariance function.

In other words, if I do:

```python
covfcn_bounds = {
	"l": [1e-4, 2],
	"sigmaf": [1e-4, 4],
	"sigman": [1e-6, 4]
}
covfcn_bounds = [v for v in covfcn_bounds.values()]
sexp = squaredExponential(bounds=covfcn_bounds)
```

Those custom bounds will be lost in the first call to `_lmlik`. The same happens in this [line](https://github.com/josejimenezluna/pyGPGO/blob/5c9c838f1875cdea9dfa574a4c757a400448a0f6/pyGPGO/surrogates/GaussianProcess.py#L98) and this [line](https://github.com/josejimenezluna/pyGPGO/blob/295a7b17b0358ee73ad554e487961635986fdadc/pyGPGO/surrogates/GaussianProcess.py#L197). Other files are also affected (`tStudentProcess`, `GaussianProcessMCMC`, and `tStudentProcessMCMC`).

**Comment by josejimenezluna** [comment]
Dear @bacalfa,

Many thanks for noticing this. I'm currently flagging this as a bug, and will fix asap.
