### ISSUE TITLE
Support for constrained optimization

### ISSUE THREAD

**Issue by miha-skalic** [josejimenezluna/pyGPGO#4]
Hello there, 

first of all, I would like to thank you for the package.

Secondly, I have a request. Many real-world optimization problems of interest have constraints which are unknown a priori. It would be very cool if this package could implement constrained Bayesian optimization as reported in this paper: https://arxiv.org/abs/1403.5607

Essentially, one would define probabilistic constraints of the sort:

![image](https://user-images.githubusercontent.com/7152667/27083154-da9d525a-5047-11e7-8b19-0b02fa223ec2.png)

And place a GP surrogate on each constraint. These are updated in each evaluation of the target function as well.

Best, 
Miha

**Comment by hawk31** [comment]
Hi, 

This functionality was also suggested by https://www.reddit.com/r/MachineLearning/comments/6e6x8c/p_pygpgo_another_python_package_for_bayesian/di9ct52/

I will consider adding it in the near future.

**Comment by jacktang** [comment]
Hello @josejimenezluna , since the issue was marked as completed, can you provide one example to show how to add constraints?
